name: update-calendar

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Generate calendar
        run: python generate.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add calendar.ics
          git commit -m "update calendar" || echo "no changes"
          git push
