name: update-calendar

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download ICS
        run: |
          URL="https://uspu.ru/education/eios/schedule/calendar/calendar_filter/calendar_БХ-2331_22.04.2026%2012%3A00%3A00_13.05.2026%2012%3A00%3A00.ics"

          curl --http1.1 \
               --retry 5 \
               --retry-delay 3 \
               --fail \
               -L "$URL" -o calendar_new.ics || true

      - name: Validate ICS content
        run: |
          echo "Validating file..."

          if [ -s calendar_new.ics ] && grep -q "BEGIN:VCALENDAR" calendar_new.ics; then
            echo "Valid ICS"
            mv calendar_new.ics calendar.ics
          else
            echo "Invalid or missing ICS — keeping old version"

            if [ ! -f calendar.ics ]; then
              echo "Creating fallback calendar"
              cat <<EOF > calendar.ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Uni Schedule//RU
END:VCALENDAR
EOF
            fi
          fi

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add calendar.ics

          git commit -m "update calendar" || echo "no changes"

          git push
